server:
  port: 8089

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/regnews
    username: regnews
    password: regnews
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
groq:
  api:
    key: ${GROQ_API_KEY}
    url: https://api.groq.com/openai/v1/chat/completions
finnhub:
  api:
    key: ${FINNHUB_API_KEY}
    url: https://finnhub.io/api/v1/news